# Generated by Django 5.2 on 2025-05-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                ("cover_image_url", models.CharField(max_length=255, null=True)),
                ("price", models.FloatField(null=True)),
                ("city", models.CharField(max_length=255, null=True)),
                ("kind", models.CharField(max_length=255, null=True)),
                ("size", models.CharField(max_length=255, null=True)),
                ("status", models.CharField(max_length=255, null=True)),
                ("contact_name", models.CharField(max_length=255, null=True)),
                ("company", models.CharField(max_length=255, null=True)),
                ("summary", models.TextField(max_length=255, null=True)),
            ],
            options={
                "db_table": "asset_properties",
            },
        ),
    ]
