---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: sort-simple-yaml

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ["--config", "./pyproject.toml"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args: ["--config", "./.flake8"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--settings-file", "./pyproject.toml"]

  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.7.0

default_stages:
  - pre-commit
