# Generated by Django 5.2 on 2025-04-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="vehicle",
            table="vehicles",
        ),
    ]
