# Generated by Django 5.2 on 2025-05-06 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0002_alter_vehicle_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="wheel",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
